__author__ = 'Zero'
from django.utils.translation import pgettext_lazy

STATUS_DISPLAY_CHOICES = (
    ("CREATE INSTANCE", pgettext_lazy("Action of an Instance", u"Create Instance")),
    ("DELETE INSTANCE", pgettext_lazy("Action of an Instance", u"Delete Instance")),
    ("UPDATE INSTANCE", pgettext_lazy("Action of an Instance", u"Update Instance")),
    ("EVACUATE", pgettext_lazy("Action of an Instance", u"Evacuate")),
    ("RESTORE INSTANCE", pgettext_lazy("Action of an Instance", u"Restore Instance")),
    ("STOP INSTANCE", pgettext_lazy("Action of an Instance", u"Stop Instance")),
    ("START INSTANCE", pgettext_lazy("Action of an Instance", u"Start")),
    ("REBOOT INSTANCE", pgettext_lazy("Action of an Instance", u"Reboot Instance")),
    ("REBUILD INSTANCE", pgettext_lazy("Action of an Instance", u"Rebuild")),
    ("REVERT RESIZE", pgettext_lazy("Action of an Instance", u"Revert Resize")),
    ("CONFIRM RESIZE", pgettext_lazy("Action of an Instance", u"Confirm Resize")),
    ("RESIZE INSTANCE", pgettext_lazy("Action of an Instance", u"Resize")),
    ("MIGRATE", pgettext_lazy("Action of an Instance", u"Migrate")),
    ("PAUSE", pgettext_lazy("Action of an Instance", u"Pause")),
    ("UNPAUSE", pgettext_lazy("Action of an Instance", u"Unpause")),
    ("SUSPEND", pgettext_lazy("Action of an Instance", u"Suspend")),
    ("RESUME", pgettext_lazy("Action of an Instance", u"Resume")),
    ("RESCUE", pgettext_lazy("Action of an Instance", u"Rescue")),
    ("UNRESCUE", pgettext_lazy("Action of an Instance", u"Unrescue")),
    ("CHANGE PASSWORD", pgettext_lazy("Action of an Instance", u"Change Password")),
    ("SHELVE", pgettext_lazy("Action of an Instance", u"Shelve")),
    ("UNSHELVE", pgettext_lazy("Action of an Instance", u"Unshelve")),
    ("CREATE SNAPSHOT", pgettext_lazy("Action of an Instance", u"Create Snapshot")),
    ("CREATE DEVSNAPSHOT", pgettext_lazy("Action of an Instance", u"Create Devsnapshot")),
    ("REVERT DEVSNAPSHOT", pgettext_lazy("Action of an Instance", u"Revert Devsnapshot")),
    ("DELETE DEVSNAPSHOT", pgettext_lazy("Action of an Instance", u"Delete Devsnapshot")),
    ("UPDATE NAME", pgettext_lazy("Action of an Instance", u"Update Name")),
    ("UPDATE USB", pgettext_lazy("Action of an Instance", u"Update Usb")),
    ("UPDATE SCREEN", pgettext_lazy("Action of an Instance", u"Update Screen")),
    ("REALLOCATE INSTANCE", pgettext_lazy("Action of an Instance", u"Reallocate Instance")),
    ("ATTACH/DETACH CDROM", pgettext_lazy("Action of an Instance", u"Attach/Detach CDrom")),
    ("CREATE AGGREGATE", pgettext_lazy("Action of an Instance", u"Create Aggregate")),
    ("UPDATE AGGREGATE", pgettext_lazy("Action of an Instance", u"Update Aggregate")),
    ("DELETE AGGREGATE", pgettext_lazy("Action of an Instance", u"Delete Aggregate")),
    ("CREATE FLAVOR", pgettext_lazy("Action of an Instance", u"Create Flavor")),
    ("DELETE FLAVOR", pgettext_lazy("Action of an Instance", u"Delete Flavor")),
    ("CREATE VOLUME", pgettext_lazy("Action of a volume", u"Create Volume")),
    ("DELETE VOLUME", pgettext_lazy("Action of a volume", u"Delete Volume")),
    ("UPDATE VOLUME", pgettext_lazy("Action of a volume", u"Update Volume")),
    ("UPDATE VOLUME STATUS", pgettext_lazy("Action of a volume", u"Update Volume Status")),
    ("CREATE VOLUME SNAPSHOT", pgettext_lazy("Action of a volume", u"Create Volume Snapshot")),
    ("DELETE VOLUME SNAPSHOT", pgettext_lazy("Action of a volume", u"Delete Volume Snapshot")),
    ("UPLOAD IMAGE TO VOLUME", pgettext_lazy("Action of a volume", u"Upload Image To Volume")),
    ("REGISTER LICENSE", pgettext_lazy("Action of admin", u"Register License")),
    ("ADD AGENT", pgettext_lazy("Action of a Network", u"Add Agent")),
    ("DELETE AGENT", pgettext_lazy("Action of a Network", u"Delete Agent")),
    ("CREATE PORT", pgettext_lazy("Action of a Network", u"Create Port")),
    ("UPDATE PORT", pgettext_lazy("Action of a Network", u"Update Port")),
    ("DELETE PORT", pgettext_lazy("Action of a Network", u"Delete Port")),
    ("CREATE SUBNET", pgettext_lazy("Action of a Network", u"Create Subnet")),
    ("UPDATE SUBNET", pgettext_lazy("Action of a Network", u"Update Subnet")),
    ("DELETE SUBNET", pgettext_lazy("Action of a Network", u"Delete Subnet")),
    ("CREATE NETWORK", pgettext_lazy("Action of a Network", u"Create Network")),
    ("UPDATE NETWORK", pgettext_lazy("Action of a Network", u"Update Network")),
    ("DELETE NETWORK", pgettext_lazy("Action of a Network", u"Delete Network")),
    ("CREATE TENANT", pgettext_lazy("Action of a Pool", u"Create Tenant")),
    ("UPDATE TENANT", pgettext_lazy("Action of a Pool", u"Update Tenant")),
    ("DELETE TENANT", pgettext_lazy("Action of a Pool", u"Delete Tenant")),
    ("ADD INTERFACE", pgettext_lazy("Action of a Router", u"Add Interface")),
    ("SET GATEWAY", pgettext_lazy("Action of a Router", u"Set Gateway")),
    ("REMOVE INTERFACE", pgettext_lazy("Action of a Router", u"Remove Interface")),
    ("CREATE ROUTER", pgettext_lazy("Action of a Router", u"Create Router")),
    ("UPDATE ROUTER", pgettext_lazy("Action of a Router", u"Update Router")),
    ("DELETE ROUTER", pgettext_lazy("Action of a Router", u"Delete Router")),
    ("DELETE USER", pgettext_lazy("Action of an User", u"Delete User")),
    ("CLEAR GATEWAY", pgettext_lazy("Action of a Router", u"Clear Gateway")),
    ("CREATE USER", pgettext_lazy("Action of an User", u"Create User")),
    ("UPDATE USER", pgettext_lazy("Action of an User", u"Update User")),
    ("TOGGLE USER", pgettext_lazy("Action of an User", u"Toggle User")),
    ("DISABLE USER", pgettext_lazy("Action of an User", u"Disable User")),
    ("ENABLE USER", pgettext_lazy("Action of an User", u"Enable User")),
    ("DELETE IMAGE", pgettext_lazy("Action of an Image", u"Delete Image")),
    ("CREATE IMAGE", pgettext_lazy("Action of an Image", u"Create Image")),
    ("UPDATE IMAGE", pgettext_lazy("Action of an Image", u"Update Image")),
    ("DELETE TEMPLATE", pgettext_lazy("Action of an Image", u"Delete Template")),
    ("ATTACH VOLUME", pgettext_lazy("Action of a volume", u"Attach Volume")),
    ("DETACH VOLUME", pgettext_lazy("Action of a volume", u"Detach Volume")),
    ("LOGIN", pgettext_lazy("Action of admin", u"Login")),
    ("LOGOUT", pgettext_lazy("Action of admin", u"Logout")),
    ("REQUEST REMOTE ASSISTANCE", pgettext_lazy("Action of an Instance", u"Request Remote Assistance")),
    ("WAIT REMOTE ASSISTANCE", pgettext_lazy("Action of an Instance", u"Wait Remote Assistance")),
)
RESULT_DISPLAY_CHOICES = (
    ("SUCCESS", pgettext_lazy("Status of result", u"Success")),
    ("FAILURE", pgettext_lazy("Status of result", u"Failure")),
)
